version: '3.7'

services:
  eventservice:
    image: jevent/event-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"


    networks:
      backend:
        aliases:
            - "eventservice"
networks:
  backend:
    driver: bridge